disable optimize_webui
FileNotFoundError: [Errno 2] No such file or directory: '/chromium-137.0.7151.40/out/Release/gen/chrome/browser/resources/tab_search/bundled/shared.rollup.js.map'

split_new_tab_page.ts was added to the tab_search bundle, which causes
rollup_js.py to call rollup with "--chunkFileNames shared.rollup.js",
thus creating a third rolled up file. However, instead of creating all
three (tab_search.rollup.js.map, split_new_tab_page.rollup.js.map, and
shared.rollup.js.map), it only creates the first two, leading to that
error.

Other bundles (such as new_tab_page) have no problems calling
--chunkFileNames, but for whatever reason tab_search does. I suspect
this is related to some silent failure around rollup 3.x, but we'll need
to come back to it later; for now, just disable optimize_webui so that
rollup isn't even called on this stuff.